[workspace]
members = [
    "core",
    "derive",
    "wrappers",
]

[workspace.dependencies]
rand = "0.8.5"
once_cell = "1.13.1"
parking_lot = "0.12.1"

bcs = { version = "0.1.4" }
rmp-serde = { version = "1.1.1" }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = { version = "1.0.87" }

threadpool = "1.8.1" # used in a background cleaner

primitive-types-0-12 = { package = "primitive-types", version = "0.12", default-features = false }
primitive-types-0-11 = { package = "primitive-types", version = "0.11", default-features = false }
primitive-types-0-10 = { package = "primitive-types", version = "0.10", default-features = false }

rocksdb = { version = "0.20.1", default-features = false }
sled = { package = "vsdbsled", version = "0.34.7-p1", features = ["io_uring"] }

ruc = { version = "4.1.0", features = ["crypto"] }
vsdb_derive = { path = "derive", version = "0.45.0" }
vsdb_core = { path = "core", version = "0.52.1" }
